language: ruby

bundler_args: '--binstubs --without documentation'
script: "rake test"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DEVISE_ORM=mongoid
  - DEVISE_ORM=active_record
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - Gemfile
services:
  - mongodb
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "TRiqvuM4i/QmRDWjUSNitE5/P91BOzDkNl53+bZjjtxcISCswZtmECWBR7n9\n3xwqCOU1o2lfohxZ32OHOj/Nj7o+90zWJfWxcv+if0hIXRiil62M5pg0lZUd\nyJ4M5VQ0lSWo5he1OUrXhSabPJeaK3B8yT/tdh+qO5yzR+vb/jc="
