language: ruby

rvm:
  - 2.1
  - 2.2

gemfile:
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable
  - Gemfile

matrix:
  include:
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.rails-5.0-alpha
  allow_failures:
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.rails-5.0-alpha
services:
  - mongodb

sudo: false

cache: bundler

env:
  matrix:
    - DEVISE_ORM=mongoid
    - DEVISE_ORM=active_record

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bundle exec rake test"

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Q3M+kmude3FjisibEeeGe0wSMXgvwLH+vL7Zrx9//q4QtkfnrQ/BBMvY9KXxPEsNF+eys4YopYjTkJ8uRmeboUATW/oQ4Jrv3+u3zkIHK2sFn/Q2cQWpK5w+CbgEnHPjKYnUu34b09njXTgDlr/mqtbPqrKeZ1dLlpKXCB/q4GY=
