script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - Gemfile
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - carlos@plataformatec.com.br
    - rodrigo.flores@plataformatec.com.br
    - rafael.franca@plataformatec.com.br
