name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-main
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        env:
          - DEVISE_ORM=active_record
          - DEVISE_ORM=mongoid
        exclude:
          - gemfile: Gemfile
            env: DEVISE_ORM=mongoid
          - gemfile: gemfiles/Gemfile-rails-main
            env: DEVISE_ORM=mongoid
          - gemfile: gemfiles/Gemfile-rails-7-0
            env: DEVISE_ORM=mongoid
          - gemfile: gemfiles/Gemfile-rails-6-1
            env: DEVISE_ORM=mongoid
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '3.2'
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: '3.1'
          - gemfile: gemfiles/Gemfile-rails-6-0
            env: DEVISE_ORM=mongoid
    # TODO: lock `ubunty-20.04` due to older Ruby version compatibility, change to `ubuntu-latest` again when dropping older Ruby support.
    # https://github.com/ruby/setup-ruby/issues/496#issuecomment-1520662740
    runs-on: ubuntu-20.04
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'default' }}
          rubygems: ${{ env.RUBYGEMS_VERSION || 'latest' }}
      - uses: supercharge/mongodb-github-action@1.9.0
        if: ${{ matrix.env == 'DEVISE_ORM=mongoid' }}
      - run: bundle exec rake
